server:
  port: 8280
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fsrcs?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/**
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    cache-enabled: true
  type-aliases-package: edu.wbu.fsrcs
  mapper-locations: classpath*:mapper/*.xml
